version: '3.8'

services:
  my_gradio_app:
    #build:  ./app/build/Dockerfile 
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    ports:
      - "7860:7860" # Open port
    volumes: 
      - .:/work/point2cad
    runtime: nvidia
    command: python -m app.src.main
    deploy:   
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
volumes:
  point2cad:
